### ISSUE TITLE
"Size mismatched key(s)" error when loading parameters in Torch unet example  

### ISSUE THREAD

**Issue by masahi** [openvinotoolkit/nncf#1004]
Running UNet example in https://github.com/openvinotoolkit/nncf/tree/develop/examples/torch/semantic_segmentation with int8 checkpoint https://storage.openvinotoolkit.org/repositories/nncf/models/develop/unet_mapillary_int8.pth resulted in the following error. 

nncf version: https://github.com/openvinotoolkit/nncf/commit/1bd52822dec121a7c7ffaab7364e21232dd07ef4
PyTorch: 1.10

Command: `$ python main.py -m {test,export} --config=configs/unet_mapillary_int8.json --resume unet_mapillary_int8.pth --data mapillary/ --to-onnx unet_int8.onnx --batch-size 4`

```
...
WARNING:nncf:Different size of value of 'nncf_module.up_path.0.up.pre_ops.0.op.scale' in resuming dictionary (torch.Size([1024, 1, 1, 1])) and in model (torch.Size([1, 512,
1, 1]))
WARNING:nncf:Different size of value of 'nncf_module.up_path.1.up.pre_ops.0.op.scale' in resuming dictionary (torch.Size([512, 1, 1, 1])) and in model (torch.Size([1, 256, 1
, 1]))
WARNING:nncf:Different size of value of 'nncf_module.up_path.2.up.pre_ops.0.op.scale' in resuming dictionary (torch.Size([256, 1, 1, 1])) and in model (torch.Size([1, 128, 1
, 1]))
WARNING:nncf:Different size of value of 'nncf_module.up_path.3.up.pre_ops.0.op.scale' in resuming dictionary (torch.Size([128, 1, 1, 1])) and in model (torch.Size([1, 64, 1,
 1]))
Traceback (most recent call last):
  File "main.py", line 621, in <module>
    main(sys.argv[1:])
  File "main.py", line 617, in main
    start_worker(main_worker, config)
  File "/home/masa/projects/ml/nncf/examples/torch/common/execution.py", line 116, in start_worker
    mp.spawn(main_worker, nprocs=config.ngpus_per_node, args=(config,))
  File "/home/masa/anaconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/masa/anaconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/masa/anaconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:


-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/masa/anaconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/masa/projects/ml/nncf/examples/torch/semantic_segmentation/main.py", line 534, in main_worker
    load_state(model, model_state_dict, is_resume=True)
  File "/home/masa/projects/ml/nncf/nncf/torch/checkpoint_loading.py", line 50, in load_state
    key_matcher.handle_problematic_keys()
  File "/home/masa/projects/ml/nncf/nncf/torch/checkpoint_loading.py", line 441, in handle_problematic_keys
    self._processed_keys.handle_problematic(self._is_resume, num_matched_params == self._num_params_to_load)
  File "/home/masa/projects/ml/nncf/nncf/torch/checkpoint_loading.py", line 141, in handle_problematic
    raise RuntimeError(error_msg)
RuntimeError: Error(s) when loading model parameters:
        Size mismatched key(s):
                "nncf_module.up_path.3.up.pre_ops.0.op.scale",
                "nncf_module.up_path.2.up.pre_ops.0.op.scale",
                "nncf_module.up_path.1.up.pre_ops.0.op.scale",
                "nncf_module.up_path.0.up.pre_ops.0.op.scale".
```

**Comment by vshampor** [comment]
Greetings, @masahi! We've recently updated the `develop` state and associated checkpoints. Could you please update your NNCF state to the latest develop branch tip and try again?

**Comment by masahi** [comment]
@vshampor I updated to the latest branch but hit the same error.

**Comment by vshampor** [comment]
@masahi, sorry, I haven't mentioned that but should have - you might want to redownload the .pth checkpoint at https://storage.openvinotoolkit.org/repositories/nncf/models/develop/unet_mapillary_int8.pth because the underlying file has also changed.

**Comment by masahi** [comment]
Yes, I downloaded the checkpoint today and tried again, still same error. The checkpoint file is not different from the one I was using when I opened this issue.

**Comment by vshampor** [comment]
@masahi please use the following link:
https://storage.openvinotoolkit.org/repositories/nncf/models/develop/torch/unet_mapillary_int8.pth

Notice that it has "torch" in the URL while your URL and mine above does not have "torch". This is an older link that goes back to 1.x versions of NNCF and the underlying checkpoints are incompatible. Sorry about this happening - the checkpoints under the older path should not be accessible at all, and we'll fix it shortly.

**Comment by masahi** [comment]
@vshampor Worked!!

```
>>>> Avg. loss: 1.0655 | Mean IoU: 0.5570                                                                                                                                    unlabeled: nan                                                                                                                                                               
road: 0.9041                                                                                                                                                                 sidewalk: 0.5244                                                                                                                                                             
building: 0.8163                                                                                                                                                             wall: 0.3566                                                                                                                                                                 
fence: 0.4535                                                                                                                                                                pole: 0.4005                                                                                                                                                                 
traffic_light: 0.5354                                                                                                                                                        traffic_sign: 0.6569                                                                                                                                                         
vegetation: 0.8702                                                                                                                                                           terrain: 0.6354                                                                                                                                                              
sky: 0.9656                                                                                                                                                                  person: 0.5967                                                                                                                                                               
rider: 0.2890                                                                                                                                                                car: 0.7709                                                                                                                                                                  
truck: 0.4311                                                                                                                                                                
bus: 0.4319                                                                                                                                                                  
train: 0.0852
motorcycle: 0.3798
bicycle: 0.4788
```

I've tried other model (torch SSD512-VGG, TF MaskRCNN, RetinaNet, Yolo4), all worked. Thank you very much for your help.
