### ISSUE TITLE
Support Transformers 4.16.0

### ISSUE THREAD

**Issue by dkurt** [openvinotoolkit/nncf#1093]
There is an error with https://github.com/huggingface/transformers/blob/master/examples/pytorch/token-classification/run_ner.py example on `transformers==4.16.1`:

```
[WARNING|trainer_callback.py:304] 2022-01-31 06:54:46,782 >> The Trainer will not work properly if you don't have a `DefaultFlowCallback` in its callbacks. You
should add one before training with `trainer.add_callback(DefaultFlowCallback). The current list ofcallbacks is
:DefaultFlowCallback
[INFO|<string>:578] 2022-01-31 06:54:46,783 >> The following columns in the training set  don't have a corresponding argument in `NNCFNetwork.forward` and have been ignored: pos_tags, id, tokens, ner_tags, chunk_tags.
Traceback (most recent call last):
  File "examples/pytorch/token-classification/run_ner.py", line 596, in <module>
    main()
  File "examples/pytorch/token-classification/run_ner.py", line 527, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "<string>", line 1242, in train
  File "<string>", line 827, in create_optimizer_and_scheduler
  File "<string>", line 851, in create_optimizer
  File "<string>", line 904, in get_optimizer_cls_and_kwargs
ValueError: Trainer cannot instantiate unsupported optimizer: OptimizerNames.ADAMW_HF
```

**Comment by MaximProshin** [comment]
@AlexKoff88 , @ljaljushkin , is it still valid?

**Comment by ljaljushkin** [comment]
Patch [was updated](https://github.com/openvinotoolkit/nncf/pull/1328) to the latest Transformers version 4.23.1.

[Sanity test](https://github.com/openvinotoolkit/nncf/blob/develop/tests/torch/test_sanity_third_party.py#L234) for training via run_ner.py was working with this patch (build 23)
