### ISSUE TITLE
[Bug] input_low must be a CUDA tensor

### ISSUE THREAD

**Issue by dkurt** [openvinotoolkit/nncf#1099]
**NNCF**: 2.1.0
**PyTorch**: 1.9.1+cu102
**Transformers**: 4.15.0

```
Traceback (most recent call last):
  File "run_audio_classification.py", line 372, in <module>
    main()
  File "run_audio_classification.py", line 346, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "<string>", line 1364, in train
  File "<string>", line 1934, in training_step
  File "<string>", line 1969, in compute_loss
  File "/home/dkurtaev/transformers/examples/pytorch/audio-classification/venv3/lib/python3.6/site-packages/nncf/torch/dynamic_graph/wrappers.py", line 156, in wrapped
    return module_call(self, *args, **kwargs)
  File "/home/dkurtaev/transformers/examples/pytorch/audio-classification/venv3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dkurtaev/transformers/examples/pytorch/audio-classification/venv3/lib/python3.6/site-packages/nncf/torch/debug.py", line 69, in decorated
    retval = forward_func(self, *args, **kwargs)
  File "/home/dkurtaev/transformers/examples/pytorch/audio-classification/venv3/lib/python3.6/site-packages/nncf/torch/nncf_network.py", line 247, in forward
    args, kwargs = self._wrap_inputs_fn(args, kwargs)
  File "/home/dkurtaev/transformers/examples/pytorch/audio-classification/venv3/lib/python3.6/site-packages/nncf/torch/dynamic_graph/io_handling.py", line 106, in wrap_inputs
    bound_model_params.arguments[param_name] = nncf_model_input(bound_model_params.arguments[param_name])
  File "/home/dkurtaev/transformers/examples/pytorch/audio-classification/venv3/lib/python3.6/site-packages/nncf/torch/dynamic_graph/wrappers.py", line 133, in wrapped
    result = ctx.execute_post_hooks(op_address, result)
  File "/home/dkurtaev/transformers/examples/pytorch/audio-classification/venv3/lib/python3.6/site-packages/nncf/torch/dynamic_graph/context.py", line 227, in execute_post_hooks
    outputs = hook(outputs)
  File "/home/dkurtaev/transformers/examples/pytorch/audio-classification/venv3/lib/python3.6/site-packages/nncf/torch/quantization/algo.py", line 761, in __call__
    return storage[self.quantizer_storage_key](*args, **kwargs)
  File "/home/dkurtaev/transformers/examples/pytorch/audio-classification/venv3/lib/python3.6/site-packages/nncf/torch/dynamic_graph/wrappers.py", line 158, in wrapped
    retval = module_call(self, *args, **kwargs)
  File "/home/dkurtaev/transformers/examples/pytorch/audio-classification/venv3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dkurtaev/transformers/examples/pytorch/audio-classification/venv3/lib/python3.6/site-packages/nncf/torch/quantization/layers.py", line 166, in forward
    return self.quantize(x, execute_traced_op_as_identity=False)
  File "/home/dkurtaev/transformers/examples/pytorch/audio-classification/venv3/lib/python3.6/site-packages/nncf/torch/quantization/layers.py", line 566, in quantize
    self.eps, skip=execute_traced_op_as_identity)
  File "/home/dkurtaev/transformers/examples/pytorch/audio-classification/venv3/lib/python3.6/site-packages/nncf/torch/dynamic_graph/wrappers.py", line 123, in wrapped
    result = operator(*args, **kwargs)
  File "/home/dkurtaev/transformers/examples/pytorch/audio-classification/venv3/lib/python3.6/site-packages/nncf/torch/quantization/quantize_functions.py", line 184, in asymmetric_quantize
    return QuantizeAsymmetric.apply(input_, input_low_tuned, input_range_tuned, level_low, level_high, levels)
  File "/home/dkurtaev/transformers/examples/pytorch/audio-classification/venv3/lib/python3.6/site-packages/nncf/torch/quantization/quantize_functions.py", line 74, in forward
    output = QuantizedFunctionsCUDA.Quantize_forward(input_, input_low, input_range, levels)
RuntimeError: input_low.is_cuda()INTERNAL ASSERT FAILED at "/home/dkurtaev/transformers/examples/pytorch/audio-classification/venv3/lib/python3.6/site-packages/nncf/torch/extensions/src/quantization/cuda/functions_cuda.cpp":15, please report a bug to PyTorch. input_low must be a CUDA tensor
```

steps to reproduce: on  https://github.com/huggingface/transformers/tree/v4.15.0/examples/pytorch/audio-classification sample with HuggingFace patch.

```bash
#!/bin/bash

export NCCL_P2P_DISABLE=1

python run_audio_classification.py \
    --model_name_or_path anton-l/wav2vec2-base-ft-keyword-spotting \
    --dataset_name superb \
    --dataset_config_name ks \
    --output_dir wav2vec2-base-ft-keyword-spotting \
    --overwrite_output_dir \
    --remove_unused_columns False \
    --do_eval \
    --do_train \
    --nncf_config nncf_config.json \
    --learning_rate 3e-5 \
    --max_length_seconds 1 \
    --attention_mask False \
    --warmup_ratio 0.1 \
    --num_train_epochs 5 \
    --per_device_train_batch_size 32 \
    --gradient_accumulation_steps 4 \
    --per_device_eval_batch_size 32 \
    --dataloader_num_workers 4 \
    --logging_strategy steps \
    --logging_steps 10 \
    --evaluation_strategy epoch \
    --save_strategy epoch \
    --load_best_model_at_end True \
    --metric_for_best_model accuracy \
    --save_total_limit 3 \
    --seed 0
```
<details>
<summary> nncf_config.json </summary>

```json
{
    "input_info": [
        {
            "sample_size": [1, 16000],
            "type": "float"
        }
    ],
    "compression": {
        "algorithm": "quantization",
        "initializer": {
            "range": {
                "num_init_samples": 32,
                "type": "percentile",
                "params":
                {
                    "min_percentile": 0.01,
                    "max_percentile": 99.99
                }
            },

            "batchnorm_adaptation": {
                "num_bn_adaptation_samples": 200
            }
        },
        "activations":
        {
            "mode": "asymmetric"
        },
        "weights":
        {
            "mode": "symmetric",
            "signed": true,
            "per_channel": true
        }
    }
}
```

</details>

**Comment by dkurt** [comment]
Problem appears after training resumed after model saving. Workarounded by changing save policy:
```
    --save_strategy steps \
    --save_steps 1500 \
```

**Comment by dkurt** [comment]
Please review a workaround: https://github.com/openvinotoolkit/nncf/pull/1101
