### ISSUE TITLE
Can not open the shared file quantized_functions_cuda.so

### ISSUE THREAD

**Issue by sunrainyg** [openvinotoolkit/nncf#1333]
I encounter with this error (I'm using torch1.9.0_cu111, cudatoolkit=11.3):

Traceback (most recent call last):
  File "tools/train.py", line 345, in <module>
    main()
  File "tools/train.py", line 341, in main
    meta=meta)
  File "/dev/cloud-end/mmdetection-ote/mmdet/apis/train.py", line 146, in train_detector
    is_accuracy_aware=nncf_is_acc_aware_training_set)
  File "/dev/cloud-end/mmdetection-ote/mmdet/integration/nncf/compression.py", line 119, in wrap_nncf_model
    from nncf.torch import create_compressed_model
  File "/root/anaconda3/envs/nncf/lib/python3.7/site-packages/nncf/torch/__init__.py", line 42, in <module>
    from nncf.torch.binarization import algo as binarization_algo
  File "/root/anaconda3/envs/nncf/lib/python3.7/site-packages/nncf/torch/binarization/algo.py", line 29, in <module>
    from nncf.torch.algo_selector import PT_COMPRESSION_ALGORITHMS
  File "/root/anaconda3/envs/nncf/lib/python3.7/site-packages/nncf/torch/algo_selector.py", line 20, in <module>
    from nncf.torch.nncf_network import NNCFNetwork
  File "/root/anaconda3/envs/nncf/lib/python3.7/site-packages/nncf/torch/nncf_network.py", line 71, in <module>
    from nncf.torch.quantization.layers import QUANTIZATION_MODULES
  File "/root/anaconda3/envs/nncf/lib/python3.7/site-packages/nncf/torch/quantization/__init__.py", line 14, in <module>
    from . import layers
  File "/root/anaconda3/envs/nncf/lib/python3.7/site-packages/nncf/torch/quantization/layers.py", line 36, in <module>
    from nncf.torch.quantization.quantize_functions import symmetric_quantize, asymmetric_quantize, \
  File "/root/anaconda3/envs/nncf/lib/python3.7/site-packages/nncf/torch/quantization/quantize_functions.py", line 18, in <module>
    from nncf.torch.quantization.extensions import QuantizedFunctionsCPU, QuantizedFunctionsCUDA
  File "/root/anaconda3/envs/nncf/lib/python3.7/site-packages/nncf/torch/quantization/extensions.py", line 79, in <module>
    QuantizedFunctionsCUDA = QuantizedFunctionsCUDALoader.load()
  File "/root/anaconda3/envs/nncf/lib/python3.7/site-packages/nncf/torch/quantization/extensions.py", line 69, in load
    verbose=False)
  File "/root/anaconda3/envs/nncf/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1092, in load
    keep_intermediates=keep_intermediates)
  File "/root/anaconda3/envs/nncf/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1318, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/root/anaconda3/envs/nncf/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1701, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: /root/.cache/torch_extensions/nncf/quantized_functions_cuda/1.9.0+cu111/quantized_functions_cuda.so: cannot open shared object file: No such file or directory

**Comment by AlexKoff88** [comment]
Hi,

First of all, you are using torch1.9.0_cu111 (which looks like built for CUDA 1.11) but with cudatoolkit 11.3.

Second of all, it looks like you try to run the script on behalf of the superuser. Can you try to do the same thing on behalf of any other user? The NNCF will compile PyTorch extensions and place them into ~/.cache/torch_extensions/.... It need the correct environment variables to find CUDAToolkit and compiler for that.

**Comment by vshampor** [comment]
This looked like a misconfiguration problem. In such cases it helps to remove `~/.cache/torch_extensions/` and try again.
