### ISSUE TITLE
fatal error: Python.h: No such file or directory

### ISSUE THREAD

**Issue by i3abghany** [openvinotoolkit/nncf#1395]
When I run the example in `examples/torch/classification` using the command: python ./main.py --mode=train --data=./cifar-10-python --config=./configs/mixed_precision/resnet50_imagenet_mixed_int_hawq.json --log-dir=./hawq_runs/4`. I get an error that `Python.h` header file isn't found.

```
/home/srinija/nncf/nncf/torch/__init__.py:23: UserWarning: NNCF provides best results with torch==1.9.1, while current torch version is 1.12.1+cu102 - consider switching to torch==1.9.1

warnings.warn("NNCF provides best results with torch=={bkc}, "

Traceback (most recent call last):

File "/home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/utils/cpp_extension.py", line 1808, in _run_ninja_build

subprocess.run(

File "/usr/lib/python3.8/subprocess.py", line 516, in run

raise CalledProcessError(retcode, process.args,

subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

File "./main.py", line 42, in <module>

from examples.torch.common.execution import ExecutionMode

File "/home/srinija/nncf/examples/torch/common/execution.py", line 19, in <module>

from nncf.torch.utils import manual_seed

File "/home/srinija/nncf/nncf/torch/__init__.py", line 42, in <module>

from nncf.torch.binarization import algo as binarization_algo

File "/home/srinija/nncf/nncf/torch/binarization/algo.py", line 30, in <module>

from nncf.torch.algo_selector import PT_COMPRESSION_ALGORITHMS

File "/home/srinija/nncf/nncf/torch/algo_selector.py", line 20, in <module>

from nncf.torch.nncf_network import NNCFNetwork

File "/home/srinija/nncf/nncf/torch/nncf_network.py", line 71, in <module>

from nncf.torch.quantization.layers import QUANTIZATION_MODULES

File "/home/srinija/nncf/nncf/torch/quantization/__init__.py", line 14, in <module>

from . import layers

File "/home/srinija/nncf/nncf/torch/quantization/layers.py", line 36, in <module>

from nncf.torch.quantization.quantize_functions import symmetric_quantize, asymmetric_quantize, \

File "/home/srinija/nncf/nncf/torch/quantization/quantize_functions.py", line 18, in <module>

from nncf.torch.quantization.extensions import QuantizedFunctionsCPU, QuantizedFunctionsCUDA

File "/home/srinija/nncf/nncf/torch/quantization/extensions.py", line 76, in <module>

QuantizedFunctionsCPU = QuantizedFunctionsCPULoader.load()

File "/home/srinija/nncf/nncf/torch/quantization/extensions.py", line 50, in load

return load(cls.name(),

File "/home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/utils/cpp_extension.py", line 1202, in load

return _jit_compile(

File "/home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/utils/cpp_extension.py", line 1425, in _jit_compile

_write_ninja_file_and_build_library(

File "/home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/utils/cpp_extension.py", line 1537, in _write_ninja_file_and_build_library

_run_ninja_build(

File "/home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/utils/cpp_extension.py", line 1824, in _run_ninja_build

raise RuntimeError(message) from e

RuntimeError: Error building extension 'quantized_functions_cpu': [1/3] c++ -MMD -MF tensor_funcs.o.d -DTORCH_EXTENSION_NAME=quantized_functions_cpu -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/srinija/nncf/nncf/torch/extensions/include -isystem /home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/include -isystem /home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/include/torch/csrc/api/include -isystem /home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-

linux-x86_64.egg/torch/include/TH -isystem /home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/include/THC -isystem /home/srinija/venv3/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /home/srinija/nncf/nncf/torch/extensions/src/common/cpu/tensor_funcs.cpp -o tensor_funcs.o

FAILED: tensor_funcs.o

c++ -MMD -MF tensor_funcs.o.d -DTORCH_EXTENSION_NAME=quantized_functions_cpu -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/srinija/nncf/nncf/torch/extensions/include -isystem /home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/include -isystem /home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/include/torch/csrc/api/include -isystem /home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/include/TH -isystem /home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/include/THC -isystem /home/srinija/venv3/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /home/srinija/nncf/nncf/torch/extensions/src/common/cpu/tensor_funcs.cpp -o tensor_funcs.o

In file included from /home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/include/torch/csrc/Device.h:3:0,

from /home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/include/torch/csrc/api/include/torch/python.h:8,

from /home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/include/torch/extension.h:6,

from /home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/include/torch/csrc/api/include/torch/torch.h:6,

from /home/srinija/nncf/nncf/torch/extensions/include/common_cpu_funcs.h:4,

from /home/srinija/nncf/nncf/torch/extensions/src/common/cpu/tensor_funcs.cpp:1:

/home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/include/torch/csrc/python_headers.h:10:10: fatal error: Python.h: No such file or directory

#include <Python.h>

^~~~~~~~~~

compilation terminated.

[2/3] c++ -MMD -MF functions_cpu.o.d -DTORCH_EXTENSION_NAME=quantized_functions_cpu -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/srinija/nncf/nncf/torch/extensions/include -isystem /home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/include -isystem /home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/include/torch/csrc/api/include -isystem /home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/include/TH -isystem /home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/include/THC -isystem /home/srinija/venv3/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /home/srinija/nncf/nncf/torch/extensions/src/quantization/cpu/functions_cpu.cpp -o functions_cpu.o

FAILED: functions_cpu.o

c++ -MMD -MF functions_cpu.o.d -DTORCH_EXTENSION_NAME=quantized_functions_cpu -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/srinija/nncf/nncf/torch/extensions/include -isystem /home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/include -isystem /home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/include/torch/csrc/api/include -isystem /home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/include/TH -isystem /home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/include/THC -isystem /home/srinija/venv3/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /home/srinija/nncf/nncf/torch/extensions/src/quantization/cpu/functions_cpu.cpp -o functions_cpu.o

In file included from /home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/include/torch/csrc/Device.h:3:0,

from /home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/include/torch/csrc/api/include/torch/python.h:8,

from /home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/include/torch/extension.h:6,

from /home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/include/torch/csrc/api/include/torch/torch.h:6,

from /home/srinija/nncf/nncf/torch/extensions/include/common_cpu_funcs.h:4,

from /home/srinija/nncf/nncf/torch/extensions/src/quantization/cpu/functions_cpu.cpp:1:

/home/srinija/venv3/lib/python3.8/site-packages/torch-1.12.1-py3.8-linux-x86_64.egg/torch/include/torch/csrc/python_headers.h:10:10: fatal error: Python.h: No such file or directory

#include <Python.h>

^~~~~~~~~~

compilation terminated.

ninja: build stopped: subcommand failed.
```

Does anyone have an idea how to resolve this issue? I appreciate any help you can provide.

**Comment by ljaljushkin** [comment]
Hello Mahmoud!

Seems like there's some issue with installation header files for python-dev, which is needed to build Python extensions.
NNCF builds such extensions for faster quantization and binarization.

I recommend installing python-dev system-wide.
```
sudo apt-get install python3-dev
```

**Comment by i3abghany** [comment]
Thank you @ljaljushkin for the timely response. However, python3-dev is installed and it appears that this isn't the problem.

**Comment by vshampor** [comment]
> Thank you @ljaljushkin for the timely response. However, python3-dev is installed and it appears that this isn't the problem.

Check this SO answer out:
https://askubuntu.com/questions/1261759/python-h-file-not-found-on-ubuntu-20-04-even-after-installing-python-dev

**Comment by ljaljushkin** [comment]
@i3abghany, have you eventually managed to resolve the issue? Did the answer above help with it?

**Comment by thancaocuong** [comment]
@ljaljushkin  You can solve it by run this command
```bash
sudo apt-get install python-numpy
```
