### ISSUE TITLE
filter_pruning error, RuntimeError: cannot register a hook on a tensor that doesn't require gradient

### ISSUE THREAD

**Issue by Wang-zipeng** [openvinotoolkit/nncf#199]
I'm trying to train "filter_pruning", my configs is:
        {
            "algorithm": "filter_pruning",
            "params": {
                "schedule": "baseline",
                "pruning_target": 0.3
            }
        },
I can train int8 and sparsity with maskrcnn with this code,  but when i trying to train filter_pruning, i got this error.
Fully traceback is:
Traceback (most recent call last):
  File "./train.py", line 216, in main
    meta=meta)
  File "/home/amax/projects/mech_learning/mmdet/apis/train.py", line 80, in train_detector
    model, compression_ctrl = wrap_nncf_model(model, cfg, data_loaders[0])
  File "/home/amax/projects/mech_learning/mmdet/core/nncf/utils.py", line 41, in wrap_nncf_model
    model, nncf_config, dummy_forward_fn=dummy_forward, resuming_state_dict=resuming_state_dict
  File "/home/amax/git_projects/nncf_pytorch/nncf/model_creation.py", line 126, in create_compressed_model
    compression_ctrl = compressed_model.commit_compression_changes()
  File "/home/amax/git_projects/nncf_pytorch/nncf/nncf_network.py", line 421, in commit_compression_changes
    composite_controller.add(algo_builder.build_controller(self))
  File "/home/amax/git_projects/nncf_pytorch/nncf/pruning/filter_pruning/algo.py", line 40, in build_controller
    self.config)
  File "/home/amax/git_projects/nncf_pytorch/nncf/pruning/filter_pruning/algo.py", line 65, in __init__
    self._scheduler = scheduler_cls(self, params)
  File "/home/amax/git_projects/nncf_pytorch/nncf/pruning/schedulers.py", line 76, in __init__
    self._set_pruning_level()
  File "/home/amax/git_projects/nncf_pytorch/nncf/pruning/schedulers.py", line 82, in _set_pruning_level
    self.algo.set_pruning_rate(self.current_pruning_level)
  File "/home/amax/git_projects/nncf_pytorch/nncf/pruning/filter_pruning/algo.py", line 87, in set_pruning_rate
    self.zero_grads_for_pruned_modules()
  File "/home/amax/git_projects/nncf_pytorch/nncf/pruning/base_algo.py", line 198, in zero_grads_for_pruned_modules
    self._hooks.append(weight.register_hook(partial_hook))
  File "/home/amax/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 230, in register_hook
    raise RuntimeError("cannot register a hook on a tensor that "
RuntimeError: cannot register a hook on a tensor that doesn't require gradient

**Comment by vanyalzr** [comment]
Hi @Wang-zipeng,

Thanks for pointing out this bug. There was no proper handling of frozen layers in filter pruning. You can apply the following quick fix for your case: #200.
I suspect you used a Mask-RCNN model with a ResNet50 backbone from mmdetection here, which by default has the first stage of the backbone frozen (`frozen_stages=1` param in the backbone config from mmdet). If you wish to prune this first stage of the backbone as well, I'd suggest you unfreeze it during training (by setting `frozen_stages=-1`).

**Comment by Wang-zipeng** [comment]
@vanyalzr 
Thank you for your so quick reply. Yes you are right, we are trying to use mmdetection mask_rcnn_r50_fpn and we must use a instance segmentation not a detection model.
I'm sorry report so much bug

**Comment by vanyalzr** [comment]
Closing since the issue was addressed in a merged PR.
