### ISSUE TITLE
Mobilenetv2 FP32 quant to INT8, but INT8 benchmark_app Failed Argument shapes are inconsistent.

### ISSUE THREAD

**Issue by KiwiHana** [openvinotoolkit/nncf#2103]
openvino 2023.0.1
OS: Ubuntu 22.04

(1) convert pytorch model to ONNX FP32 model 

```
python mmdeploy/tools/deploy.py \
    mmdeploy/configs/mmpretrain/classification_onnxruntime_static.py \
    mmpretrain/configs/mobilenet_v2/mobilenet-v2_8xb32_in1k.py \
    mobilenet_v2_batch256_imagenet_20200708-3b2dc3af.pth \
    mmdetection/demo/demo.jpg \
    --work-dir model_onnx/mobilenetv2_static/ \
    --device cpu \
    --dump-info
```

(2) check ONNX FP32 Model is OK.
```
$conda activate ov2023.0.1
$model_onnx/mobilenetv2_static$ benchmark_app -m end2end.onnx -d CPU
[Step 4/11] Reading model files
[ INFO ] Loading model files
[ INFO ] Read model took 33.26 ms
[ INFO ] Original model I/O parameters:
[ INFO ] Model inputs:
[ INFO ]     input (node: input) : f32 / [...] / [1,3,224,224]
[ INFO ] Model outputs:
[ INFO ]     output (node: output) : f32 / [...] / [1,1000]
……
[Step 11/11] Dumping statistics report
[ INFO ] Execution Devices:['CPU']
[ INFO ] Count:            51625 iterations
[ INFO ] Duration:         60014.22 ms
[ INFO ] Latency:
[ INFO ]    Median:        6.19 ms
[ INFO ]    Average:       5.74 ms
[ INFO ]    Min:           2.00 ms
[ INFO ]    Max:           90.91 ms
[ INFO ] Throughput:   860.21 FPS
```

(3) NNCF ONNX FP32 model to INT8 model 
https://github.com/openvinotoolkit/nncf/blob/develop/examples/post_training_quantization/onnx/mobilenet_v2/main.py

 ```
$python main.py
[2/7] Save INT8 model: /home/a380/Downloads/kiwi/MTL/model_onnx/mobilenetv2_static/end2end_int8.onnx
[3/7] Benchmark FP32 model:
[ INFO ] Count:            13940 iterations
[ INFO ] Duration:         15007.75 ms
[ INFO ] Latency:
[ INFO ]    Median:        5.09 ms
[ INFO ]    Average:       5.31 ms
[ INFO ]    Min:           1.92 ms
[ INFO ]    Max:           54.52 ms
[ INFO ] Throughput:   928.85 FPS
[4/7] Benchmark INT8 model:
Traceback (most recent call last):
  File "main.py", line 143, in <module>
    int8_fps = run_benchmark(int8_model_path, shape=[1, 3, 224, 224], verbose=True)
  File "main.py", line 68, in run_benchmark
    cmd_output = subprocess.check_output(command, shell=True)  # nosec
  File "/home/a380/miniconda3/envs/ov2023.0.1/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/a380/miniconda3/envs/ov2023.0.1/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'benchmark_app -m /home/a380/Downloads/kiwi/MTL/model_onnx/mobilen    etv2_static/end2end_int8.onnx -d CPU -api async -t 15 -shape [1,3,224,224]' returned non-zero exit status     1.

```

main.py can convert FP32 to INT8, but benchmark_app failed.
```
model_onnx/mobilenetv2_static$ benchmark_app -m end2end_int8.onnx -d CPU -shape [1,3,224,224]
[Step 1/11] Parsing and validating input arguments
[ INFO ] Parsing input parameters
[Step 2/11] Loading OpenVINO Runtime
[ INFO ] OpenVINO:
[ INFO ] Build ................................. 2023.0.1-11005-fa1c41994f3-releases/2023/0
[ INFO ]
[ INFO ] Device info:
[ INFO ] CPU
[ INFO ] Build ................................. 2023.0.1-11005-fa1c41994f3-releases/2023/0
[ INFO ]
[ INFO ]
[Step 3/11] Setting device configuration
[ WARNING ] Performance hint was not explicitly specified in command line. Device(CPU) performance hint will be set to PerformanceMode.THROUGHPUT.
[Step 4/11] Reading model files
[ INFO ] Loading model files
[ ERROR ] Check 'false' failed at src/inference/src/core.cpp:100:
Check 'false' failed at src/frontends/onnx/frontend/src/core/graph.cpp:391:
While validating ONNX node '<Node(QuantizeLinear): QuantizeLinear_/backbone/conv1/activate/Clip_output_0_1>':
Check 'ov::PartialShape::broadcast_merge_into(data_pshape, get_input_partial_shape(i), m_auto_broadcast)' failed at src/core/src/op/fake_quantize.cpp:47:
While validating node 'opset1::FakeQuantize FakeQuantize_400 (/backbone/conv1/activate/Clip[0]:f32[1,32,112,112], Constant_396[0]:f32[32], Constant_399[0]:f32[32], Constant_391[0]:f32[1], Constant_392[0]:f32[1]) -> (dynamic[...])' with friendly_name 'FakeQuantize_400':
Argument shapes are inconsistent.


Traceback (most recent call last):
  File "/home/a380/miniconda3/envs/ov2023.0.1/lib/python3.8/site-packages/openvino/tools/benchmark/main.py", line 363, in main
    model = benchmark.read_model(args.path_to_model)
  File "/home/a380/miniconda3/envs/ov2023.0.1/lib/python3.8/site-packages/openvino/tools/benchmark/benchmark.py", line 69, in read_model
    return self.core.read_model(model_filename, weights_filename)
RuntimeError: Check 'false' failed at src/inference/src/core.cpp:100:
Check 'false' failed at src/frontends/onnx/frontend/src/core/graph.cpp:391:
While validating ONNX node '<Node(QuantizeLinear): QuantizeLinear_/backbone/conv1/activate/Clip_output_0_1>':
Check 'ov::PartialShape::broadcast_merge_into(data_pshape, get_input_partial_shape(i), m_auto_broadcast)' failed at src/core/src/op/fake_quantize.cpp:47:
While validating node 'opset1::FakeQuantize FakeQuantize_400 (/backbone/conv1/activate/Clip[0]:f32[1,32,112,112], Constant_396[0]:f32[32], Constant_399[0]:f32[32], Constant_391[0]:f32[1], Constant_392[0]:f32[1]) -> (dynamic[...])' with friendly_name 'FakeQuantize_400':
Argument shapes are inconsistent.

```

**Comment by kshpv** [comment]
@KiwiHana Hello!
To handle your problem could you provide an ONNX FP32 model?

**Comment by KiwiHana** [comment]
[end2end.onnx.zip](https://github.com/openvinotoolkit/nncf/files/12512852/end2end.onnx.zip)

Please use attach mobilenetV2 FP32 end2end.onnx. Just modify name end2end.onnx.zip to end2end.onnx

**Comment by kshpv** [comment]
I could not reproduce your issue. The model is quantized and infered succesfully through `benchmark_app`. Which version of NNCF and OpenVINO do you use?
NNCF commit - ae7e0c2f0760fae001564603d72d6ed401ce5313
OpenVINO verion - 2023.0.1-11005-fa1c41994f3-releases/2023/0
The model that I got - [int8_model.onnx.zip](https://github.com/openvinotoolkit/nncf/files/12513461/int8_model.onnx.zip)
Please, to use a model just change **int8_model.onnx.zip** to **int8_model.onnx**
