### ISSUE TITLE
RuntimeError: Model expects 2 inputs, but 1 are provided.

### ISSUE THREAD

**Issue by KiwiHana** [openvinotoolkit/nncf#2136]
Hello, how to convert FP32 to INT8 model when a model have 2 inputs "image[1,3,640,640], scale_factor[1,2]"
openvino-dev=2023.1.0.dev20230811
nncf=2.5.0

Step (1) convert model to IR FP32 model
```
git clone https://github.com/PaddlePaddle/PaddleDetection.git

cd PaddleDetection/
pip install -r requirements.txt
pip install paddlepaddle

python tools/export_model.py -c configs/ppyoloe/ppyoloe_crn_l_300e_coco.yml --output_dir=output_inference -o weights=https://paddledet.bj.bcebos.com/models/ppyoloe_crn_l_300e_coco.pdparams

mo -m output_inference/ppyoloe_crn_l_300e_coco/model.pdmodel --output_dir=output_inference/ --compress_to_fp16 False --model_name=ppyoloe_crn_l_300e_coco 

benchmark_app -m output_inference/ppyoloe_crn_l_300e_coco.xml -t 5  -data_shape "image[1,3,640,640],scale_factor[1,2]"
```

Step(2) : Then I convert IR FP32 model to INT8 by this script 
https://github.com/openvinotoolkit/nncf/blob/develop/examples/post_training_quantization/openvino/mobilenet_v2/main.py

```
$ python main.py
2023-09-13 21:21:57.850473: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-09-13 21:21:57.882024: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, tensorflow, openvino
Statistics collection:   0%|                                                           | 0/300 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/kiwi/ov/uniview/main_ov.py", line 144, in <module>
    ov_quantized_model = nncf.quantize(ov_model, calibration_dataset)
  File "/home/kiwi/miniconda3/envs/ov2023.0.1/lib/python3.9/site-packages/nncf/quantization/quantize_model.py", line 78, in quantize
    return quantize_impl(
  File "/home/kiwi/miniconda3/envs/ov2023.0.1/lib/python3.9/site-packages/nncf/openvino/quantization/quantize_model.py", line 258, in quantize_impl
    return quantize_fn(
  File "/home/kiwi/miniconda3/envs/ov2023.0.1/lib/python3.9/site-packages/nncf/telemetry/decorator.py", line 71, in wrapped
    retval = fn(*args, **kwargs)
  File "/home/kiwi/miniconda3/envs/ov2023.0.1/lib/python3.9/site-packages/nncf/openvino/quantization/quantize_model.py", line 115, in native_quantize_impl
    quantized_model = quantization_algorithm.apply(model, dataset=calibration_dataset)
  File "/home/kiwi/miniconda3/envs/ov2023.0.1/lib/python3.9/site-packages/nncf/quantization/algorithms/algorithm.py", line 58, in apply
    return self._apply(model, statistic_points=None, dataset=dataset)
  File "/home/kiwi/miniconda3/envs/ov2023.0.1/lib/python3.9/site-packages/nncf/quantization/algorithms/post_training/algorithm.py", line 184, in _apply
    statistics_aggregator.collect_statistics(modified_model)
  File "/home/kiwi/miniconda3/envs/ov2023.0.1/lib/python3.9/site-packages/nncf/openvino/statistics/aggregator.py", line 34, in collect_statistics
    super().collect_statistics(model)
  File "/home/kiwi/miniconda3/envs/ov2023.0.1/lib/python3.9/site-packages/nncf/common/tensor_statistics/aggregator.py", line 58, in collect_statistics
    outputs = engine.infer(input_data)
  File "/home/kiwi/miniconda3/envs/ov2023.0.1/lib/python3.9/site-packages/nncf/openvino/engine.py", line 69, in infer
    self._check_input_data_format(input_data)
  File "/home/kiwi/miniconda3/envs/ov2023.0.1/lib/python3.9/site-packages/nncf/openvino/engine.py", line 53, in _check_input_data_format
    raise RuntimeError(f"Model expects {self.number_of_inputs} inputs, but {actual_num_inputs} are provided.")
RuntimeError: Model expects 2 inputs, but 1 are provided.
```

**Comment by KiwiHana** [comment]
def transform_fn(data_item):
    images, _ = data_item
    inputs = {"image":images,
              "scale_factor":torch.randn((1, 2))}
    return inputs
