### ISSUE TITLE
derivative for aten::hardsigmoid_backward is not implemented

### ISSUE THREAD

**Issue by chamecall** [openvinotoolkit/nncf#2180]
trying to quantize (mixed precision, hawq) mobilenet_v3 from timm having Hardsigmoid activation I obtain the following error:

```
Traceback (most recent call last):
  File "/home/machinelearning/.pyenv/versions/3.9.13/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/machinelearning/.pyenv/versions/3.9.13/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/machinelearning/projects/human-detection/person_detection/train_qat.py", line 568, in <module>
    cli()
  File "/home/machinelearning/.pyenv/versions/pytorch2/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/machinelearning/.pyenv/versions/pytorch2/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/machinelearning/.pyenv/versions/pytorch2/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/machinelearning/.pyenv/versions/pytorch2/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/machinelearning/projects/human-detection/person_detection/train_qat.py", line 564, in cli
    main(cfg, experiment_dir)
  File "/home/machinelearning/projects/human-detection/person_detection/train_qat.py", line 424, in main
    compression_ctrl, model = create_compressed_model(model, nncf_config)
  File "/home/machinelearning/.pyenv/versions/pytorch2/lib/python3.9/site-packages/nncf/telemetry/decorator.py", line 71, in wrapped
    retval = fn(*args, **kwargs)
  File "/home/machinelearning/.pyenv/versions/pytorch2/lib/python3.9/site-packages/nncf/torch/model_creation.py", line 132, in create_compressed_model
    compressed_model = builder.apply_to(nncf_network)
  File "/home/machinelearning/.pyenv/versions/pytorch2/lib/python3.9/site-packages/nncf/torch/compression_method_api.py", line 122, in apply_to
    transformation_layout = self.get_transformation_layout(model)
  File "/home/machinelearning/.pyenv/versions/pytorch2/lib/python3.9/site-packages/nncf/torch/compression_method_api.py", line 143, in get_transformation_layout
    layout = self._get_transformation_layout(model)
  File "/home/machinelearning/.pyenv/versions/pytorch2/lib/python3.9/site-packages/nncf/torch/quantization/algo.py", line 635, in _get_transformation_layout
    self._pt_quantizer_setup = self._get_quantizer_setup(target_model)
  File "/home/machinelearning/.pyenv/versions/pytorch2/lib/python3.9/site-packages/nncf/torch/quantization/algo.py", line 723, in _get_quantizer_setup
    single_config_quantizer_setup = self._get_single_config_quantizer_setup(target_model)
  File "/home/machinelearning/.pyenv/versions/pytorch2/lib/python3.9/site-packages/nncf/torch/quantization/algo.py", line 716, in _get_single_config_quantizer_setup
    single_config_quantizer_setup = setup_generator.generate_setup()
  File "/home/machinelearning/.pyenv/versions/pytorch2/lib/python3.9/site-packages/nncf/torch/quantization/algo.py", line 404, in generate_setup
    single_config_quantizer_setup = disambiguator.select_final_quantizer_setup(
  File "/home/machinelearning/.pyenv/versions/pytorch2/lib/python3.9/site-packages/nncf/torch/quantization/algo.py", line 321, in select_final_quantizer_setup
    final_quantizer_setup = intermediate_ctrl.init_precision(
  File "/home/machinelearning/.pyenv/versions/pytorch2/lib/python3.9/site-packages/nncf/torch/quantization/algo.py", line 1468, in init_precision
    return initializer.apply_init()
  File "/home/machinelearning/.pyenv/versions/pytorch2/lib/python3.9/site-packages/nncf/torch/quantization/precision_init/hawq_init.py", line 268, in apply_init
    traces_per_layer = self._calc_traces(self._criterion_fn, self._criterion, self._iter_number, self._tolerance)
  File "/home/machinelearning/.pyenv/versions/pytorch2/lib/python3.9/site-packages/nncf/torch/quantization/precision_init/hawq_init.py", line 503, in _calc_traces
    raise error
  File "/home/machinelearning/.pyenv/versions/pytorch2/lib/python3.9/site-packages/nncf/torch/quantization/precision_init/hawq_init.py", line 493, in _calc_traces
    avg_traces = trace_estimator.get_average_traces(max_iter=iter_number, tolerance=tolerance)
  File "/home/machinelearning/.pyenv/versions/pytorch2/lib/python3.9/site-packages/nncf/torch/quantization/hessian_trace.py", line 139, in get_average_traces
    avg_traces_per_iter.append(self._calc_avg_traces_per_param())
  File "/home/machinelearning/.pyenv/versions/pytorch2/lib/python3.9/site-packages/nncf/torch/quantization/hessian_trace.py", line 157, in _calc_avg_traces_per_param
    vhp_curr = torch.autograd.grad(
  File "/home/machinelearning/.pyenv/versions/pytorch2/lib/python3.9/site-packages/torch/autograd/__init__.py", line 303, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: derivative for aten::hardsigmoid_backward is not implemented
```
it happens during compressed model creation:
`    compression_ctrl, model = create_compressed_model(model, nncf_config)`

**Comment by chamecall** [comment]
adding the activation to ignored_scope in the config doesn't really help:
```
    "ignored_scopes": [
        "{re}.*Hardsigmoid*"
    ]
```

**Comment by alexsu52** [comment]
@ljaljushkin, please take a look.

**Comment by ljaljushkin** [comment]
Greeting, @chamecall!
I've reproduced your error and made sure that `ignored_scopes` has nothing to do with the issue.
The problem happens when we estimate Hessian by calculation of derivative from gradients. 
```python
torch.autograd.grad(gradients, ...)
```
The model is supposed to have an implemented derivative for all operations, otherwise the method won't work. 
`mobilenet-v3` from timm does not meet this criterion with not implemented `aten::hardsigmoid_backward`.

**Comment by chamecall** [comment]
> Greeting, @chamecall! I've reproduced your error and made sure that `ignored_scopes` has nothing to do with the issue. The problem happens when we estimate Hessian by calculation of derivative from gradients.
> 
> ```python
> torch.autograd.grad(gradients, ...)
> ```
> 
> The model is supposed to have an implemented derivative for all operations, otherwise the method won't work. `mobilenet-v3` from timm does not meet this criterion with not implemented `aten::hardsigmoid_backward`.

`when we estimate Hessian by calculation of derivative from gradients` that's about computing precision for different layers based on specified compression_ratio for hawq algo, right? cause when I don't specify the hawq type there's no any error.
And if so then why can't we just ignore the problematic scope (hardsigmoid in my case) specifying it in `ignored_scope` so that hawq wouldn't even touch it when applying Hutchinson algo?

**Comment by ljaljushkin** [comment]
> when we estimate Hessian by calculation of derivative from gradients you're talking about computing precisions for different layers based on specified compression_ratio for hawq algo, right? cause when I don't specify the hawq type there's no any error.

yes, correct

>And if so then why can't we just ignore the problematic scope (hardsigmoid in my case) specifying it in ignored_scope so that hawq wouldn't even touch it when applying Hutchinson algo?

As far as understand, you can't just ignore the problematic scope.
The gradients are calculated with respect to loss, when you take the derivative from gradients you need to propagate it through all operations from output to weight node.

```
outputs = self._model(*args, **kwargs)
loss = self._criterion_fn(outputs, target, self._criterion)

loss.backward(create_graph=True)
grads = self._parameter_handler.get_gradients()

vhp_curr = torch.autograd.grad(
    gradients, self._parameter_handler.parameters, grad_outputs=v, only_inputs=True, retain_graph=False
)
```
