### ISSUE TITLE
NNCF can not compile model: Default output not supported (opset1::VariadicSplit)

### ISSUE THREAD

**Issue by cansik** [openvinotoolkit/nncf#2943]
### 🐛 Describe the bug

The following model (YOLOX trained on COCO 80) has been converted from ONNX to OpenVINO with the most recent OpenVINO version (`openvino==2024.3.0`). I am able to read the model and compile it using the openvino framework.

However, when using nncf (`2.12.0` or `2.11.0`) to run a post-training-quantization, nncf seems not be able to compile the model (or the quantized model). Here is the full error log:

```python
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, onnx, openvino
Traceback (most recent call last):
  File "/my-project/.venv/lib/python3.11/site-packages/nncf/telemetry/decorator.py", line 72, in wrapped
    retval = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/my-project/.venv/lib/python3.11/site-packages/nncf/openvino/quantization/quantize_model.py", line 171, in native_quantize_impl
    quantized_model = quantization_algorithm.apply(model, graph, dataset=calibration_dataset)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/my-project/.venv/lib/python3.11/site-packages/nncf/quantization/algorithms/post_training/algorithm.py", line 112, in apply
    return self._pipeline.run_from_step(model, dataset, graph, 0, step_index_to_statistics)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/my-project/.venv/lib/python3.11/site-packages/nncf/quantization/algorithms/pipeline.py", line 161, in run_from_step
    step_statistics = collect_statistics(statistic_points, step_model, step_graph, dataset)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/my-project/.venv/lib/python3.11/site-packages/nncf/quantization/algorithms/pipeline.py", line 49, in collect_statistics
    statistics_aggregator.collect_statistics(model, graph)
  File "/my-project/.venv/lib/python3.11/site-packages/nncf/openvino/statistics/aggregator.py", line 36, in collect_statistics
    super().collect_statistics(model, graph)
  File "/my-project/.venv/lib/python3.11/site-packages/nncf/common/tensor_statistics/aggregator.py", line 69, in collect_statistics
    engine = factory.EngineFactory.create(model_with_outputs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/my-project/.venv/lib/python3.11/site-packages/nncf/common/factory.py", line 97, in create
    return OVNativeEngine(model)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/my-project/.venv/lib/python3.11/site-packages/nncf/openvino/engine.py", line 68, in __init__
    compiled_model = ie.compile_model(model, device_name="CPU")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/my-project/.venv/lib/python3.11/site-packages/openvino/runtime/ie_api.py", line 543, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Exception from src/inference/src/cpp/core.cpp:107:
Exception from src/inference/src/dev/plugin.cpp:53:
Check 'false' failed at src/core/src/node.cpp:148:
While validating node 'opset1::VariadicSplit VariadicSplit_31733 (opset1::Transpose /model/_head/_modules_list.14/Transpose[0]:f16[1,1,60,80,85], opset1::Constant Constant_31732[0]:i32[], opset1::Constant Constant_31731[0]:i32[3]) -> (f16[1,1,60,80,2], f16[1,1,60,80,2], f16[1,1,60,80,81])' with friendly_name 'VariadicSplit_31733':
Default output not supported
```

NNCF is able to quantize other models, however not this specific one.

### Environment

MacOS 14.6.1 (23G93)
Python 3.11.6
openvino==2024.3.0
nncf==2.12.0

### Minimal Reproducible Example

Models (ONNX and OpenVINO FP32): [yolox_n-coco126.zip](https://github.com/user-attachments/files/16849085/yolox_n-coco126.zip)

```python
import nncf
import numpy as np
import openvino as ov

ie = ov.Core()
ov_model = ie.read_model("yolox_n-coco126.xml")
# verify if compile works
compiled_model = ie.compile_model(ov_model, device_name="CPU")

# create random inputs for calibration dataset
data = [np.random.rand(*list(ov_model.inputs[0].shape)) for i in range(10)]
calibration_dataset = nncf.Dataset(data)

# run calibration
quantized_model = nncf.quantize(ov_model, calibration_dataset, target_device=nncf.TargetDevice.CPU)
```

### Are you going to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by MaximProshin** [comment]
Hi @cansik . It might be that the problem is not in NNCF but rather in OV core. Are you able to run fp32 IR?
@alexsu52 , @KodiaqQ, please take a look.

**Comment by cansik** [comment]
@MaximProshin Yes, I am able to infer the **not-quantized** model (as in the zip file). The issue is the already converted model, because the error happens at a VariadicSplit_31733 which is not part of my initial FP32 IR. I have the feeling that the conversion from FP32 IR to the quantized model introduces an issue.

```python
import openvino as ov
import numpy as np

ie = ov.Core()
ov_model = ie.read_model("yolox_n-coco126.xml")
compiled_model = ie.compile_model(ov_model, device_name="CPU")

data = [np.random.rand(*list(ov_model.inputs[0].shape)) for i in range(10)]

for image in data:
    result = compiled_model.infer_new_request(image)
    print(result)
```

Just another observation: The error messages mention a split from `f16[1,1,60,80,85]` to `f16[1,1,60,80,2], f16[1,1,60,80,2], f16[1,1,60,80,81]` which I don't understand. The model output size (85) is made up of:

- `4` coordinates per bounding box
- `1` score of the bounding box
- `80` class scores

So, splitting 85 into 2 x 2 x 81 sounds strange. But maybe it's not related at all.

**Comment by MaximProshin** [comment]
Thanks @cansik for your input! Let us investigate it.

**Comment by alexsu52** [comment]
Hello @cansik, 

I was unable to reproduce the error on Ubuntu 22.04.4 LTS. I don't have a MacOS 14.6.1 at hand, maybe you have the ability to try to reproduce the error on Ubuntu?

I used the following code:
```
import numpy as np
import openvino as ov

import nncf

ie = ov.Core()
ov_model = ie.read_model("yolox_n-coco126.xml")
# verify if compile works
compiled_model = ie.compile_model(ov_model, device_name="CPU")

# create random inputs for calibration dataset
data = [np.random.rand(*list(ov_model.inputs[0].shape)) for i in range(10)]
calibration_dataset = nncf.Dataset(data)

# run calibration
quantized_model = nncf.quantize(ov_model, calibration_dataset, target_device=nncf.TargetDevice.CPU)

# compile quantized model
compiled_model = ov.compile_model(quantized_model, device_name="CPU")

# infer quantized model
data = [np.random.rand(*list(ov_model.inputs[0].shape)) for i in range(10)]
for image in data:
    result = compiled_model.infer_new_request(image)
    print(result)

```
Log:
```
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, onnx, openvino
Statistics collection ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 10/10 • 0:00:00 • 0:00:00
Applying Fast Bias correction ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 83/83 • 0:00:01 • 0:00:00
{<ConstOutput: names[1296] shape[1,6300,85] type: f32>: array([[[9.5544519e+00, 2.7298434e+00, 1.6507185e+01, ...,
         3.7067155e-03, 2.6080022e-03, 5.4875589e-03],
        [1.9601833e+01, 3.1198211e+00, 4.5591270e+01, ...,
         4.0092268e-03, 2.7277325e-03, 6.3792681e-03],
        [2.3994541e+01, 3.0223267e+00, 6.6814796e+01, ...,
         4.6339692e-03, 2.1023683e-03, 5.7476824e-03],
        ...,
        [5.4471881e+02, 4.7531622e+02, 2.2754669e+02, ...,
         7.9799127e-03, 3.1561612e-03, 4.3274318e-03],
        [5.5659113e+02, 4.7675394e+02, 1.7245645e+02, ...,
         8.0637308e-03, 3.5190431e-03, 4.6755737e-03],
        [6.4897430e+02, 4.7675394e+02, 2.2036101e+02, ...,
         9.2306612e-03, 3.4228340e-03, 4.7319587e-03]]], dtype=float32)}
{<ConstOutput: names[1296] shape[1,6300,85] type: f32>: array([[[9.5544519e+00, 2.7298434e+00, 1.6507185e+01, ...,
         3.7067155e-03, 2.6080022e-03, 5.4875589e-03],
        [1.9601833e+01, 3.1198211e+00, 4.5591270e+01, ...,
         4.0092268e-03, 2.7277325e-03, 6.3792681e-03],
        [2.3994541e+01, 3.0223267e+00, 6.6814796e+01, ...,
         4.6339692e-03, 2.1023683e-03, 5.7476824e-03],
        ...,
        [5.4471881e+02, 4.7531622e+02, 2.2754669e+02, ...,
         7.9799127e-03, 3.1561612e-03, 4.3274318e-03],
        [5.5659113e+02, 4.7675394e+02, 1.7245645e+02, ...,
         8.0637308e-03, 3.5190431e-03, 4.6755737e-03],
        [6.4897430e+02, 4.7675394e+02, 2.2036101e+02, ...,
         9.2306612e-03, 3.4228340e-03, 4.7319587e-03]]], dtype=float32)}
{<ConstOutput: names[1296] shape[1,6300,85] type: f32>: array([[[9.5544519e+00, 2.7298434e+00, 1.6507185e+01, ...,
         3.7067155e-03, 2.6080022e-03, 5.4875589e-03],
        [1.9601833e+01, 3.1198211e+00, 4.5591270e+01, ...,
         4.0092268e-03, 2.7277325e-03, 6.3792681e-03],
        [2.3994541e+01, 3.0223267e+00, 6.6814796e+01, ...,
         4.6339692e-03, 2.1023683e-03, 5.7476824e-03],
        ...,
        [5.4471881e+02, 4.7531622e+02, 2.2754669e+02, ...,
         7.9799127e-03, 3.1561612e-03, 4.3274318e-03],
        [5.5659113e+02, 4.7675394e+02, 1.7245645e+02, ...,
         8.0637308e-03, 3.5190431e-03, 4.6755737e-03],
        [6.4897430e+02, 4.7675394e+02, 2.2036101e+02, ...,
         9.2306612e-03, 3.4228340e-03, 4.7319587e-03]]], dtype=float32)}
{<ConstOutput: names[1296] shape[1,6300,85] type: f32>: array([[[9.5544519e+00, 2.7298434e+00, 1.6507185e+01, ...,
         3.7067155e-03, 2.6080022e-03, 5.4875589e-03],
        [1.9601833e+01, 3.1198211e+00, 4.5591270e+01, ...,
         4.0092268e-03, 2.7277325e-03, 6.3792681e-03],
        [2.3994541e+01, 3.0223267e+00, 6.6814796e+01, ...,
         4.6339692e-03, 2.1023683e-03, 5.7476824e-03],
        ...,
        [5.4471881e+02, 4.7531622e+02, 2.2754669e+02, ...,
         7.9799127e-03, 3.1561612e-03, 4.3274318e-03],
        [5.5659113e+02, 4.7675394e+02, 1.7245645e+02, ...,
         8.0637308e-03, 3.5190431e-03, 4.6755737e-03],
        [6.4897430e+02, 4.7675394e+02, 2.2036101e+02, ...,
         9.2306612e-03, 3.4228340e-03, 4.7319587e-03]]], dtype=float32)}
{<ConstOutput: names[1296] shape[1,6300,85] type: f32>: array([[[9.5544519e+00, 2.7298434e+00, 1.6507185e+01, ...,
         3.7067155e-03, 2.6080022e-03, 5.4875589e-03],
        [1.9601833e+01, 3.1198211e+00, 4.5591270e+01, ...,
         4.0092268e-03, 2.7277325e-03, 6.3792681e-03],
        [2.3994541e+01, 3.0223267e+00, 6.6814796e+01, ...,
         4.6339692e-03, 2.1023683e-03, 5.7476824e-03],
        ...,
        [5.4471881e+02, 4.7531622e+02, 2.2754669e+02, ...,
         7.9799127e-03, 3.1561612e-03, 4.3274318e-03],
        [5.5659113e+02, 4.7675394e+02, 1.7245645e+02, ...,
         8.0637308e-03, 3.5190431e-03, 4.6755737e-03],
        [6.4897430e+02, 4.7675394e+02, 2.2036101e+02, ...,
         9.2306612e-03, 3.4228340e-03, 4.7319587e-03]]], dtype=float32)}
{<ConstOutput: names[1296] shape[1,6300,85] type: f32>: array([[[9.5544519e+00, 2.7298434e+00, 1.6507185e+01, ...,
         3.7067155e-03, 2.6080022e-03, 5.4875589e-03],
        [1.9601833e+01, 3.1198211e+00, 4.5591270e+01, ...,
         4.0092268e-03, 2.7277325e-03, 6.3792681e-03],
        [2.3994541e+01, 3.0223267e+00, 6.6814796e+01, ...,
         4.6339692e-03, 2.1023683e-03, 5.7476824e-03],
        ...,
        [5.4471881e+02, 4.7531622e+02, 2.2754669e+02, ...,
         7.9799127e-03, 3.1561612e-03, 4.3274318e-03],
        [5.5659113e+02, 4.7675394e+02, 1.7245645e+02, ...,
         8.0637308e-03, 3.5190431e-03, 4.6755737e-03],
        [6.4897430e+02, 4.7675394e+02, 2.2036101e+02, ...,
         9.2306612e-03, 3.4228340e-03, 4.7319587e-03]]], dtype=float32)}
{<ConstOutput: names[1296] shape[1,6300,85] type: f32>: array([[[9.5544519e+00, 2.7298434e+00, 1.6507185e+01, ...,
         3.7067155e-03, 2.6080022e-03, 5.4875589e-03],
        [1.9601833e+01, 3.1198211e+00, 4.5591270e+01, ...,
         4.0092268e-03, 2.7277325e-03, 6.3792681e-03],
        [2.3994541e+01, 3.0223267e+00, 6.6814796e+01, ...,
         4.6339692e-03, 2.1023683e-03, 5.7476824e-03],
        ...,
        [5.4471881e+02, 4.7531622e+02, 2.2754669e+02, ...,
         7.9799127e-03, 3.1561612e-03, 4.3274318e-03],
        [5.5659113e+02, 4.7675394e+02, 1.7245645e+02, ...,
         8.0637308e-03, 3.5190431e-03, 4.6755737e-03],
        [6.4897430e+02, 4.7675394e+02, 2.2036101e+02, ...,
         9.2306612e-03, 3.4228340e-03, 4.7319587e-03]]], dtype=float32)}
{<ConstOutput: names[1296] shape[1,6300,85] type: f32>: array([[[9.5544519e+00, 2.7298434e+00, 1.6507185e+01, ...,
         3.7067155e-03, 2.6080022e-03, 5.4875589e-03],
        [1.9601833e+01, 3.1198211e+00, 4.5591270e+01, ...,
         4.0092268e-03, 2.7277325e-03, 6.3792681e-03],
        [2.3994541e+01, 3.0223267e+00, 6.6814796e+01, ...,
         4.6339692e-03, 2.1023683e-03, 5.7476824e-03],
        ...,
        [5.4471881e+02, 4.7531622e+02, 2.2754669e+02, ...,
         7.9799127e-03, 3.1561612e-03, 4.3274318e-03],
        [5.5659113e+02, 4.7675394e+02, 1.7245645e+02, ...,
         8.0637308e-03, 3.5190431e-03, 4.6755737e-03],
        [6.4897430e+02, 4.7675394e+02, 2.2036101e+02, ...,
         9.2306612e-03, 3.4228340e-03, 4.7319587e-03]]], dtype=float32)}
{<ConstOutput: names[1296] shape[1,6300,85] type: f32>: array([[[9.5544519e+00, 2.7298434e+00, 1.6507185e+01, ...,
         3.7067155e-03, 2.6080022e-03, 5.4875589e-03],
        [1.9601833e+01, 3.1198211e+00, 4.5591270e+01, ...,
         4.0092268e-03, 2.7277325e-03, 6.3792681e-03],
        [2.3994541e+01, 3.0223267e+00, 6.6814796e+01, ...,
         4.6339692e-03, 2.1023683e-03, 5.7476824e-03],
        ...,
        [5.4471881e+02, 4.7531622e+02, 2.2754669e+02, ...,
         7.9799127e-03, 3.1561612e-03, 4.3274318e-03],
        [5.5659113e+02, 4.7675394e+02, 1.7245645e+02, ...,
         8.0637308e-03, 3.5190431e-03, 4.6755737e-03],
        [6.4897430e+02, 4.7675394e+02, 2.2036101e+02, ...,
         9.2306612e-03, 3.4228340e-03, 4.7319587e-03]]], dtype=float32)}
{<ConstOutput: names[1296] shape[1,6300,85] type: f32>: array([[[9.5544519e+00, 2.7298434e+00, 1.6507185e+01, ...,
         3.7067155e-03, 2.6080022e-03, 5.4875589e-03],
        [1.9601833e+01, 3.1198211e+00, 4.5591270e+01, ...,
         4.0092268e-03, 2.7277325e-03, 6.3792681e-03],
        [2.3994541e+01, 3.0223267e+00, 6.6814796e+01, ...,
         4.6339692e-03, 2.1023683e-03, 5.7476824e-03],
        ...,
        [5.4471881e+02, 4.7531622e+02, 2.2754669e+02, ...,
         7.9799127e-03, 3.1561612e-03, 4.3274318e-03],
        [5.5659113e+02, 4.7675394e+02, 1.7245645e+02, ...,
         8.0637308e-03, 3.5190431e-03, 4.6755737e-03],
        [6.4897430e+02, 4.7675394e+02, 2.2036101e+02, ...,
         9.2306612e-03, 3.4228340e-03, 4.7319587e-03]]], dtype=float32)}

```

**Comment by cansik** [comment]
@alexsu52 Thanks for testing this out. I do not have Linux at hand but on a Windows machine, the export works while on MacOS `arm64` it seem not work. I've created a quick Github action to verify the results on a clean machine (and various python versions). For MacOS there is no python 12 version, but that's not relevant here.

<img width="1724" alt="image" src="https://github.com/user-attachments/assets/a301ab0e-956a-4abc-b37c-0199b7b7239d">


It seems only MacOS `arm64` (`macos-12 = x64`, `macos-14 = arm64`) has this specific problem. 
The question is: Is it a NNCF or OpenVINO issue?

**Comment by MaximProshin** [comment]
@alvoron , it might be connected to ARM/Mac support in OV. Can you please take a look and try to reproduce it?

**Comment by alvoron** [comment]
@MaximProshin please assign the issue to me again.
It seems the issue is found on the plugin side.

**Comment by alvoron** [comment]
@cansik could you please try the following OpenVINO wheel package?
https://drive.google.com/file/d/1y6koF08SIXMsKPJjTC4wGAZIKnzfjMpN/view?usp=sharing

**Comment by cansik** [comment]
@alvoron Yes, this seems to fix the issue, thanks for investigating!

**Comment by cansik** [comment]
Sounds good for me. Thanks again!
