### ISSUE TITLE
KeyError: 'bf16'

### ISSUE THREAD

**Issue by hezhiqian01** [openvinotoolkit/nncf#2980]
### 🐛 Describe the bug

I got "KeyError: 'bf16'" when I run "examples/llm_compression/openvino/tiny_llama/main.py"
```
(ov_39) user@IntelW3Host:~/nncf/examples/llm_compression/openvino/tiny_llama$ python main.py 
Framework not specified. Using pt to export the model.
Using framework PyTorch: 2.4.1+cpu
Overriding 1 configuration item(s)
        - use_cache -> True
We detected that you are passing `past_key_values` as a tuple and this is deprecated and will be removed in v4.43. Please use an appropriate `Cache` class (https://huggingface.co/docs/transformers/v4.41.3/en/internal/generation_utils#transformers.Cache)
/home/hezhiqian/anaconda3/envs/ov_39/lib/python3.9/site-packages/optimum/exporters/openvino/model_patcher.py:489: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if sequence_length != 1:
Provided model does not contain state. It may lead to sub-optimal performance.Please reexport model with updated OpenVINO version >= 2023.3.0 calling the `from_pretrained` method with original model and `export=True` parameter
Statistics collection ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 128/128 • 0:00:14 • 0:00:00
Mixed-Precision assignment ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 154/154 • 0:00:07 • 0:00:00
INFO:nncf:Statistics of the bitwidth distribution:
┍━━━━━━━━━━━━━━━━┯━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┯━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┑
│   Num bits (N) │ % all parameters (layers)   │ % ratio-defining parameters (layers)   │
┝━━━━━━━━━━━━━━━━┿━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┿━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┥
│              8 │ 30% (20 / 156)              │ 21% (18 / 154)                         │
├────────────────┼─────────────────────────────┼────────────────────────────────────────┤
│              4 │ 70% (136 / 156)             │ 79% (136 / 154)                        │
┕━━━━━━━━━━━━━━━━┷━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┷━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┙
Applying Weight Compression ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% • 0:00:21 • 0:00:00
Provided model does not contain state. It may lead to sub-optimal performance.Please reexport model with updated OpenVINO version >= 2023.3.0 calling the `from_pretrained` method with original model and `export=True` parameter
Compiling the model to CPU ...
Traceback (most recent call last):
  File "/home/hezhiqian/nncf/examples/llm_compression/openvino/tiny_llama/main.py", line 83, in <module>
    main()
  File "/home/hezhiqian/nncf/examples/llm_compression/openvino/tiny_llama/main.py", line 74, in main
    output = model.generate(**input_ids, max_new_tokens=100)
  File "/home/hezhiqian/anaconda3/envs/ov_39/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/hezhiqian/anaconda3/envs/ov_39/lib/python3.9/site-packages/optimum/intel/openvino/modeling_decoder.py", line 671, in generate
    result = super().generate(
  File "/home/hezhiqian/anaconda3/envs/ov_39/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/hezhiqian/anaconda3/envs/ov_39/lib/python3.9/site-packages/transformers/generation/utils.py", line 2024, in generate
    result = self._sample(
  File "/home/hezhiqian/anaconda3/envs/ov_39/lib/python3.9/site-packages/transformers/generation/utils.py", line 2982, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/home/hezhiqian/anaconda3/envs/ov_39/lib/python3.9/site-packages/optimum/modeling_base.py", line 99, in __call__
    return self.forward(*args, **kwargs)
  File "/home/hezhiqian/anaconda3/envs/ov_39/lib/python3.9/site-packages/optimum/intel/openvino/modeling_decoder.py", line 494, in forward
    inputs = self.prepare_inputs(
  File "/home/hezhiqian/anaconda3/envs/ov_39/lib/python3.9/site-packages/optimum/intel/openvino/modeling_decoder.py", line 430, in prepare_inputs
    dtype = OV_TO_NP_TYPE[model_inputs.get_element_type().get_type_name()]
KeyError: 'bf16'

```

### Environment

[requirements.txt](https://github.com/user-attachments/files/17094833/requirements.txt)
Additional: Ubuntu 24.04 python-3.9.19 Intel(R) Xeon(R) w3-2435 

### Minimal Reproducible Example

```
cd examples/llm_compression/openvino/tiny_llama
python main.py
```

### Are you going to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by MaximProshin** [comment]
@alexsu52 , please take a look

**Comment by hezhiqian01** [comment]
Hi @alexsu52 

Thanks for reply.
Here is the config.json and xml file 
[config.json](https://github.com/user-attachments/files/17106700/config.json)
[openvino_model.txt](https://github.com/user-attachments/files/17106711/openvino_model.txt)

please rename the txt file to xml.

**Comment by nikita-savelyevv** [comment]
Pending fix: https://github.com/huggingface/optimum-intel/pull/911

**Comment by nikita-savelyevv** [comment]
@hezhiqian01 The fix has been merged into optimum-intel repository. Please update to the latest version of that package.
