### ISSUE TITLE
Getting an error "AttributeError: 'TracedTensor' object has no attribute 'tensor_meta' ", when trying to use the "create_compressed_model" function

### ISSUE THREAD

**Issue by llDev-Rootll** [openvinotoolkit/nncf#355]
I have a Pytorch transfer learning script for a ResNet50 model on a custom dataset to which I have been trying to integrate nncf into. I have have been following the steps given in the [Usage.md](https://github.com/openvinotoolkit/nncf/blob/develop/docs/Usage.md), and I keep getting an error when I try to wrap the torchvision ResNet model using the `create_compressed_model` function.

Line at which the error pops up : `compression_ctrl, model = create_compressed_model(model, nncf_config)`
NNCF config used : 
```
{
    "model": "resnet50",
    "pretrained": true,
    "input_info": {
        "sample_size": [1, 3, 224, 224]
    },
    "num_classes": 2,
    "batch_size": 256,
    "epochs": 23,
    "multiprocessing_distributed": false,
    "optimizer": {
        "type": "Adam",
        "base_lr": 0.001,
        "schedule_type": "multistep",
        "steps": [15, 20, 25]
    },
    "compression": [
        {
            "algorithm": "rb_sparsity",
            "params": {
                "sparsity_target": 0.61,
                "sparsity_target_epoch": 5,
                "sparsity_freeze_epoch": 10
            }
        },
        {
            "algorithm": "quantization"
        }
    ]
}
```
Model : `torchvision.models.resnet.resnet50`

System config : Intel Xeon with Nvidia M60 and 30Gb of RAM, CUDA 10.2 Pytorch 1.7.0 Python 3.8.5

Complete Error log : 
`Traceback (most recent call last):
  File "tes.py", line 52, in <module>
    comp_ctrl, compressed_model = create_compressed_model(model, nncf_config)
  File "/home/ubuntu/anaconda3/envs/torch_dev/lib/python3.8/site-packages/nncf/model_creation.py", line 116, in create_compressed_model
    graph = graph_builder.build_graph(model)
  File "/home/ubuntu/anaconda3/envs/torch_dev/lib/python3.8/site-packages/nncf/dynamic_graph/graph_builder.py", line 99, in build_graph
    self.custom_forward_fn(model)
  File "/home/ubuntu/anaconda3/envs/torch_dev/lib/python3.8/site-packages/nncf/dynamic_graph/graph_builder.py", line 135, in default_dummy_forward_fn
    return model(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/torch_dev/lib/python3.8/site-packages/nncf/dynamic_graph/wrappers.py", line 83, in wrapped
    retval = module_call(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/torch_dev/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/torch_dev/lib/python3.8/site-packages/torchvision/models/resnet.py", line 220, in forward
    return self._forward_impl(x)
  File "/home/ubuntu/anaconda3/envs/torch_dev/lib/python3.8/site-packages/torchvision/models/resnet.py", line 206, in _forward_impl
    x = self.maxpool(x)
  File "/home/ubuntu/anaconda3/envs/torch_dev/lib/python3.8/site-packages/nncf/dynamic_graph/wrappers.py", line 83, in wrapped
    retval = module_call(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/torch_dev/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/torch_dev/lib/python3.8/site-packages/torch/nn/modules/pooling.py", line 153, in forward
    return F.max_pool2d(input, self.kernel_size, self.stride,
  File "/home/ubuntu/anaconda3/envs/torch_dev/lib/python3.8/site-packages/nncf/dynamic_graph/wrappers.py", line 58, in wrapped
    node = ctx.find_operator_node(fargs, ia_op_exec_context)
  File "/home/ubuntu/anaconda3/envs/torch_dev/lib/python3.8/site-packages/nncf/dynamic_graph/context.py", line 148, in find_operator_node
    tensor_metas = make_input_infos(inputs)
  File "/home/ubuntu/anaconda3/envs/torch_dev/lib/python3.8/site-packages/nncf/dynamic_graph/trace_tensor.py", line 91, in make_input_infos
    input_infos.append(node_input.tensor_meta)
AttributeError: 'TracedTensor' object has no attribute 'tensor_meta'`

Would be really great if someone could point out where I am going wrong!

**Comment by vshampor** [comment]
@llDev-Rootll which version of NNCF and which version of PyTorch are you using? The error is specific for the case when there is a mismatch between the repo and the torch versions - namely, when the torch version is newer than the one that NNCF supports. Only since https://github.com/openvinotoolkit/nncf/pull/223 does NNCF use PyTorch 1.7.0+.

**Comment by llDev-Rootll** [comment]
I installed NNCF using pip as mentioned under installation guidelines. From the `nncf.__version__` command, I see that the NNCF version is 1.5.0

**Comment by vshampor** [comment]
@llDev-Rootll pease make sure that you are using PyTorch v1.5, as is specified in the package requirements.

**Comment by vshampor** [comment]
@llDev-Rootll did ensuring consistency between NNCF and PyTorch versions solve this issue?

**Comment by llDev-Rootll** [comment]
@vshampor I ran the setup from the develop branch of the repo to ensure consistency with PyTorch 1.7 . NNCF did start working however the command `nncf.__version__` still shows the version as 1.5

**Comment by vshampor** [comment]
@llDev-Rootll that is to be expected since the package version on a develop branch is only being updated once per release. Thanks for the feedback!
